theme: chulapa-jekyll
repository: dieghernan/leaflet-providersESP

locale                  :     es-ES
title                   : 
title_separator         :     #default [" | "]
subtitle                :   Leaflet plugin
description             : Leaflet plugin con proveedores de teselas y WMS de diferentes organismos públicos de España
timezone                : "Europe/Madrid"

og_image                :     ./assets/leaflet-providersESP.png
twitter_site            :   dieghernan
author:
  name                  :  D. Hernangomez 
  location              :  "Madrid, Spain"
gtag_id                 :  G-B7DT123587
analytics_id            :  

# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  brand:
    title   :  '<i class="fas fa-home" style="color: #FABD00"></i><span class="d-none">Home</span>'
  nav:
  - title: Preview
    url: ./preview
  - title: Visor - Webapp
    url: ./visor
  - title: Changelog
    url: https://github.com/dieghernan/leaflet-providersESP/blob/master/CHANGELOG.md
  - title   : <i class="fab fa-github fa-lg"></i> # Label
    url     : https://github.com/dieghernan/leaflet-providersESP 
    
footer:
  links:
    - label : Github # Label
      icon  : fab fa-github
      url   : https://github.com/dieghernan
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    - label: Blog
      icon: fas fa-blog
      url: https://dieghernan.github.io/
  
# C. Theme Settings


# Theme and colors
chulapa-skin: 
  highlight     :  zenburn
  skin          :  lymcha
  vars          :    
    enable-responsive-font-sizes : true
    
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 7
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
collections_dir     : 
permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      breadcrumb_list   :
        - label: Blog
          url: /blog/

# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

